#cloud-config
users:
  - name: arne
    sudo: true
    lock_passwd: true
    groups:
      - docker
    ssh_import_id:
        - gh:asmaps
    shell: /usr/bin/zsh

  - name: root
    lock_passwd: true

# disable_root: true

packages:
  - pwgen
  - zsh
  - python3
  - vim
  - git
  - tmux

package_update: true
package_upgrade: true
package_reboot_if_required: true
